const API_BASE="https://developer-lostark.game.onstove.com";
const STORAGE_KEY="loa-homework-v9";
const V8_KEY="loa-homework-v8";
const API_KEY_STORAGE="loa-homework-v9:api-key";
const V8_API_KEY="loa-homework-v8:api-key";
let filterMode="all", searchText="", taskTab="daily";

function uid(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function koParts(){const f=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"});return Object.fromEntries(f.formatToParts(new Date()).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));}
function dailyCycle(){const p=koParts();const d=new Date(Date.UTC(+p.year,+p.month-1,+p.day,12));if(+p.hour<6)d.setUTCDate(d.getUTCDate()-1);return [d.getUTCFullYear(),String(d.getUTCMonth()+1).padStart(2,"0"),String(d.getUTCDate()).padStart(2,"0")].join("-");}
function weeklyCycle(){const p=koParts();const d=new Date(Date.UTC(+p.year,+p.month-1,+p.day,12));if(+p.hour<6)d.setUTCDate(d.getUTCDate()-1);const diff=(d.getUTCDay()-3+7)%7;d.setUTCDate(d.getUTCDate()-diff);return [d.getUTCFullYear(),String(d.getUTCMonth()+1).padStart(2,"0"),String(d.getUTCDate()).padStart(2,"0")].join("-");}
function baseState(){return {meta:{dailyCycle:dailyCycle(),weeklyCycle:weeklyCycle()},settings:{characterName:"",rememberApiKey:false},apiRoster:{fetchedAt:null,characters:[]},activeCharacters:[]};}
function migrate(parsed){const s=baseState();s.settings={...s.settings,...(parsed?.settings??{})};s.apiRoster={...s.apiRoster,...(parsed?.apiRoster??{})};s.meta.dailyCycle=parsed?.meta?.dailyCycle??dailyCycle();s.meta.weeklyCycle=parsed?.meta?.weeklyCycle??weeklyCycle();s.activeCharacters=Array.isArray(parsed?.activeCharacters)?parsed.activeCharacters.map(c=>({...c,dailyTasks:Array.isArray(c.dailyTasks)?c.dailyTasks:[],weeklyTasks:Array.isArray(c.weeklyTasks)?c.weeklyTasks.map(t=>({...t,gold:Number(t.gold??0)})):[]})):[];return s;}
function load(){try{const now=localStorage.getItem(STORAGE_KEY);if(now)return migrate(JSON.parse(now));const old=localStorage.getItem(V8_KEY);if(old){const m=migrate(JSON.parse(old));localStorage.setItem(STORAGE_KEY,JSON.stringify(m));return m;}}catch{}return baseState();}
let state=load();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function applyResets(){const d=dailyCycle(),w=weeklyCycle();let changed=false;if(state.meta.dailyCycle!==d){state.activeCharacters.forEach(c=>c.dailyTasks.forEach(t=>t.current=0));state.meta.dailyCycle=d;changed=true;}if(state.meta.weeklyCycle!==w){state.activeCharacters.forEach(c=>c.weeklyTasks.forEach(t=>t.done=false));state.meta.weeklyCycle=w;changed=true;}if(changed)save();}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function keyOf(c){return `${c.serverName}::${c.characterName}`;}
function parseLevel(v){const n=Number.parseFloat(String(v??"0").replaceAll(",",""));return Number.isFinite(n)?n:0;}
function normalizeKey(v){const t=String(v??"").trim();return t.toLowerCase().startsWith("bearer ")?t.slice(7).trim():t;}
function fmtGold(n){return `${Number(n||0).toLocaleString("ko-KR")} G`;}
async function apiGet(path,key){const r=await fetch(API_BASE+path,{headers:{accept:"application/json",authorization:`bearer ${key}`}});if(!r.ok){const e=new Error(`HTTP ${r.status}`);e.status=r.status;throw e;}return r.json();}
function sibling(r){return {serverName:r?.ServerName??"",characterName:r?.CharacterName??"",characterLevel:Number(r?.CharacterLevel??0),characterClassName:r?.CharacterClassName??"",itemAvgLevelText:r?.ItemAvgLevel??"0",itemAvgLevel:parseLevel(r?.ItemAvgLevel)};}
function profile(r){if(!r||typeof r!=="object")return null;return {characterImage:r.CharacterImage??null,expeditionLevel:Number(r.ExpeditionLevel??0),guildName:r.GuildName??null,combatPower:r.CombatPower??null};}
async function pool(items,limit,fn){const out=new Array(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},worker));return out;}
async function syncRoster(){
 const name=document.getElementById("apiCharacter").value.trim(), apiKey=normalizeKey(document.getElementById("apiKey").value), msg=document.getElementById("syncMessage"), btn=document.getElementById("syncNow");
 if(!name){toast("원정대 조회 캐릭터를 입력해 주세요.");return;} if(!apiKey){toast("API Key를 입력해 주세요.");return;}
 btn.disabled=true;msg.className="sync-message";msg.textContent="원정대 목록 조회 중...";
 try{
   const raw=await apiGet(`/characters/${encodeURIComponent(name)}/siblings`,apiKey); if(!Array.isArray(raw))throw new Error("원정대 응답 형식 오류");
   const siblings=raw.map(sibling).filter(c=>c.characterName);let done=0;
   const chars=await pool(siblings,4,async c=>{let p=null;try{p=profile(await apiGet(`/armories/characters/${encodeURIComponent(c.characterName)}/profiles`,apiKey));}catch{}done++;msg.textContent=`프로필 조회 ${done}/${siblings.length}`;return {...c,profile:p};});
   chars.sort((a,b)=>a.serverName===b.serverName?b.itemAvgLevel-a.itemAvgLevel:a.serverName.localeCompare(b.serverName,"ko"));
   state.settings.characterName=name;state.settings.rememberApiKey=document.getElementById("rememberKey").checked;state.apiRoster={fetchedAt:new Date().toISOString(),characters:chars};
   const map=new Map(chars.map(c=>[keyOf(c),c]));state.activeCharacters.forEach(a=>{const n=map.get(a.key);if(n){Object.assign(a,{serverName:n.serverName,characterName:n.characterName,characterLevel:n.characterLevel,characterClassName:n.characterClassName,itemAvgLevel:n.itemAvgLevel,itemAvgLevelText:n.itemAvgLevelText,profile:n.profile});}});
   if(state.settings.rememberApiKey)localStorage.setItem(API_KEY_STORAGE,apiKey);else{localStorage.removeItem(API_KEY_STORAGE);localStorage.removeItem(V8_API_KEY);}
   save();render();msg.textContent=`${chars.length}개 캐릭터 동기화 완료`;toast("원정대 정보를 갱신했습니다.");
 }catch(e){msg.className="sync-message error";msg.textContent=e.status===401||e.status===403?"API Key를 확인해 주세요.":e.status===429?"요청 제한에 도달했습니다.":`동기화 실패: ${e.message}`;}finally{btn.disabled=false;}
}
function stats(){
 let dailyDone=0,dailyTotal=0,weeklyDone=0,weeklyTotal=0,goldPotential=0,goldEarned=0;
 state.activeCharacters.forEach(c=>{c.dailyTasks.forEach(t=>{dailyDone+=Math.min(Number(t.current||0),Number(t.target||1));dailyTotal+=Number(t.target||1);});c.weeklyTasks.forEach(t=>{weeklyTotal++;if(t.done)weeklyDone++;goldPotential+=Number(t.gold||0);if(t.done)goldEarned+=Number(t.gold||0);});});
 return {dailyDone,dailyTotal,weeklyDone,weeklyTotal,goldPotential,goldEarned};
}
function render(){
 applyResets();const s=stats();const dp=s.dailyTotal?Math.round(s.dailyDone/s.dailyTotal*100):0,wp=s.weeklyTotal?Math.round(s.weeklyDone/s.weeklyTotal*100):0;
 document.getElementById("dailyPct").textContent=`${dp}%`;document.getElementById("dailyText").textContent=`${s.dailyDone} / ${s.dailyTotal}`;document.getElementById("dailyBar").style.width=`${dp}%`;
 document.getElementById("weeklyPct").textContent=`${wp}%`;document.getElementById("weeklyText").textContent=`${s.weeklyDone} / ${s.weeklyTotal}`;document.getElementById("weeklyBar").style.width=`${wp}%`;
 document.getElementById("goldPotential").textContent=fmtGold(s.goldPotential);document.getElementById("goldEarned").textContent=`획득 ${fmtGold(s.goldEarned)}`;
 document.getElementById("characterCount").textContent=`${state.activeCharacters.length}명`;document.getElementById("rosterCount").textContent=`API 원정대 ${state.apiRoster.characters.length}명`;
 document.getElementById("lastSync").textContent=state.apiRoster.fetchedAt?`마지막 동기화 ${new Date(state.apiRoster.fetchedAt).toLocaleString("ko-KR")}`:"API 동기화 기록 없음";
 renderRows();
}
function charStats(c){const dt=c.dailyTasks.reduce((a,t)=>a+Number(t.target||1),0),dd=c.dailyTasks.reduce((a,t)=>a+Math.min(Number(t.current||0),Number(t.target||1)),0),wt=c.weeklyTasks.length,wd=c.weeklyTasks.filter(t=>t.done).length;return {dailyRemaining:dt-dd,weeklyRemaining:wt-wd};}
function visible(){const q=searchText.trim().toLowerCase();return [...state.activeCharacters].sort((a,b)=>a.favorite!==b.favorite?(a.favorite?-1:1):b.itemAvgLevel-a.itemAvgLevel).filter(c=>{const s=charStats(c);if(filterMode==="daily"&&s.dailyRemaining===0)return false;if(filterMode==="weekly"&&s.weeklyRemaining===0)return false;if(filterMode==="favorite"&&!c.favorite)return false;if(!q)return true;return [c.characterName,c.characterClassName,c.serverName,c.itemAvgLevelText].join(" ").toLowerCase().includes(q);});}
function renderRows(){const rows=document.getElementById("rows"),chars=visible();if(state.activeCharacters.length===0){rows.innerHTML=`<div class="empty-state"><strong>숙제 캐릭터가 없습니다.</strong>먼저 API 원정대를 동기화하고 캐릭터를 추가해 주세요.<br><button class="btn primary" style="margin-top:12px" onclick="openAdd()">+ 캐릭터 추가</button></div>`;return;}if(chars.length===0){rows.innerHTML=`<div class="empty-state"><strong>표시할 캐릭터가 없습니다.</strong>필터나 검색어를 바꿔 주세요.</div>`;return;}rows.innerHTML=chars.map(rowHtml).join("");}
function rowHtml(c){const img=c.profile?.characterImage;const potential=c.weeklyTasks.reduce((a,t)=>a+Number(t.gold||0),0),earned=c.weeklyTasks.filter(t=>t.done).reduce((a,t)=>a+Number(t.gold||0),0);
 return `<div class="row">
 <div class="identity"><div class="avatar">${img?`<img src="${esc(img)}" alt="">`:`<div class="avatar-fallback">${esc(c.characterClassName.slice(0,2)||"LA")}</div>`}</div><div class="meta"><div class="name-line"><button class="favorite ${c.favorite?"on":""}" onclick="toggleFavorite('${esc(c.key)}')">★</button><div class="name">${esc(c.characterName)}</div></div><div class="sub">${esc(c.characterClassName)} · <span class="ilevel">Lv.${esc(c.itemAvgLevelText)}</span> · ${esc(c.serverName)}</div></div></div>
 <div class="task-group">${c.dailyTasks.length?c.dailyTasks.map(t=>dailyPill(c,t)).join(""):`<button class="empty-task" onclick="openTasks('${esc(c.key)}','daily')">+ 일일 숙제</button>`}</div>
 <div class="task-group">${c.weeklyTasks.length?c.weeklyTasks.map(t=>weeklyPill(c,t)).join(""):`<button class="empty-task" onclick="openTasks('${esc(c.key)}','weekly')">+ 주간 숙제</button>`}</div>
 <div class="gold-cell"><div class="gold-main">${fmtGold(potential)}</div><div class="gold-sub">획득 ${fmtGold(earned)}</div></div>
 <div class="menu"><button onclick="openTasks('${esc(c.key)}','daily')">⋯</button></div>
 </div>`;}
function dailyPill(c,t){const current=Number(t.current||0),target=Math.max(1,Number(t.target||1)),done=current>=target;return `<div class="pill ${done?"done":""}"><span class="label">${esc(t.name)}</span><span class="counter"><button class="count-btn" onclick="changeDaily('${esc(c.key)}','${esc(t.id)}',-1)">−</button><span class="count-text">${current}/${target}</span><button class="count-btn" onclick="changeDaily('${esc(c.key)}','${esc(t.id)}',1)">+</button></span></div>`;}
function weeklyPill(c,t){return `<button class="pill ${t.done?"done":""}" onclick="toggleWeekly('${esc(c.key)}','${esc(t.id)}')" title="${esc(t.note||t.name)}"><span class="check">${t.done?"✓":""}</span><span class="label">${esc(t.name)}</span>${Number(t.gold||0)>0?`<span style="color:var(--gold2);font-size:8px">${Number(t.gold).toLocaleString("ko-KR")}</span>`:""}</button>`;}
function changeDaily(ck,id,delta){const c=state.activeCharacters.find(x=>x.key===ck),t=c?.dailyTasks.find(x=>x.id===id);if(!t)return;const target=Math.max(1,Number(t.target||1));t.current=Math.max(0,Math.min(target,Number(t.current||0)+delta));save();render();}
function toggleWeekly(ck,id){const c=state.activeCharacters.find(x=>x.key===ck),t=c?.weeklyTasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;save();render();}
function toggleFavorite(ck){const c=state.activeCharacters.find(x=>x.key===ck);if(!c)return;c.favorite=!c.favorite;save();render();}
function openSettings(){document.getElementById("apiCharacter").value=state.settings.characterName||"";document.getElementById("rememberKey").checked=!!state.settings.rememberApiKey;document.getElementById("apiKey").value=localStorage.getItem(API_KEY_STORAGE)||localStorage.getItem(V8_API_KEY)||"";document.getElementById("syncMessage").innerHTML="";openModal("settingsModal");}
function saveSettings(){state.settings.characterName=document.getElementById("apiCharacter").value.trim();state.settings.rememberApiKey=document.getElementById("rememberKey").checked;const k=normalizeKey(document.getElementById("apiKey").value);if(state.settings.rememberApiKey&&k)localStorage.setItem(API_KEY_STORAGE,k);else{localStorage.removeItem(API_KEY_STORAGE);localStorage.removeItem(V8_API_KEY);}save();closeModal("settingsModal");toast("설정을 저장했습니다.");}
function openAdd(){if(!state.apiRoster.characters.length){toast("먼저 설정에서 API 동기화를 해 주세요.");openSettings();return;}document.getElementById("candidateSearch").value="";renderCandidates();openModal("addModal");}
function renderCandidates(){const q=document.getElementById("candidateSearch").value.trim().toLowerCase(),active=new Set(state.activeCharacters.map(c=>c.key)),list=document.getElementById("candidateList");const arr=state.apiRoster.characters.filter(c=>!q||[c.characterName,c.characterClassName,c.serverName,c.itemAvgLevelText].join(" ").toLowerCase().includes(q));list.innerHTML=arr.map(c=>{const k=keyOf(c),added=active.has(k),img=c.profile?.characterImage;return `<label class="candidate ${added?"disabled":""}"><input class="candidate-check" type="checkbox" value="${esc(k)}" ${added?"disabled":""} onchange="updateSelected()"><div class="candidate-avatar">${img?`<img src="${esc(img)}" alt="">`:""}</div><div><div class="candidate-name">${esc(c.characterName)}</div><div class="candidate-meta">${esc(c.characterClassName)} · Lv.${esc(c.itemAvgLevelText)} · ${esc(c.serverName)}</div></div><span class="badge">${added?"등록됨":"추가 가능"}</span></label>`;}).join("")||`<div class="empty-state">검색 결과가 없습니다.</div>`;updateSelected();}
function updateSelected(){document.getElementById("selectedCount").textContent=`${document.querySelectorAll(".candidate-check:checked").length}명 선택`;}
function selectCandidates(){document.querySelectorAll(".candidate-check").forEach(c=>{if(!c.disabled)c.checked=true;});updateSelected();}
function confirmAdd(){const selected=[...document.querySelectorAll(".candidate-check:checked")],existing=new Set(state.activeCharacters.map(c=>c.key));let count=0;selected.forEach(box=>{const c=state.apiRoster.characters.find(x=>keyOf(x)===box.value);if(!c||existing.has(box.value))return;state.activeCharacters.push({key:box.value,serverName:c.serverName,characterName:c.characterName,characterLevel:c.characterLevel,characterClassName:c.characterClassName,itemAvgLevel:c.itemAvgLevel,itemAvgLevelText:c.itemAvgLevelText,profile:c.profile,favorite:false,dailyTasks:[],weeklyTasks:[]});existing.add(box.value);count++;});save();closeModal("addModal");render();toast(`${count}명 추가했습니다.`);}
function openTasks(ck,tab="daily"){const c=state.activeCharacters.find(x=>x.key===ck);if(!c)return;document.getElementById("taskCharacterKey").value=ck;document.getElementById("taskModalTitle").textContent=`${c.characterName} · 숙제 설정`;taskTab=tab;renderTaskTabs();renderEditors(c);openModal("taskModal");}
function renderTaskTabs(){document.querySelectorAll("[data-tasktab]").forEach(b=>b.classList.toggle("active",b.dataset.tasktab===taskTab));document.getElementById("dailyEditorWrap").style.display=taskTab==="daily"?"block":"none";document.getElementById("weeklyEditorWrap").style.display=taskTab==="weekly"?"block":"none";}
function renderEditors(c){document.getElementById("dailyEditor").innerHTML=c.dailyTasks.map(dailyEdit).join("");document.getElementById("weeklyEditor").innerHTML=c.weeklyTasks.map(weeklyEdit).join("");}
function dailyEdit(t){return `<div class="edit-row daily" data-id="${esc(t.id)}" data-current="${Number(t.current||0)}"><div class="edit-main"><input class="input task-name" value="${esc(t.name)}" placeholder="일일 숙제 이름"></div><input class="input target-input" type="number" min="1" value="${Math.max(1,Number(t.target||1))}" placeholder="횟수"><button class="remove" onclick="this.closest('.edit-row').remove()">✕</button></div>`;}
function weeklyEdit(t){return `<div class="edit-row" data-id="${esc(t.id)}" data-done="${t.done?"1":"0"}"><div class="edit-main"><input class="input task-name" value="${esc(t.name)}" placeholder="주간 숙제 이름"><input class="input task-note" value="${esc(t.note||"")}" placeholder="메모 (선택)"></div><select class="select task-cat">${["레이드","낙원","주간","기타"].map(cat=>`<option ${cat===t.category?"selected":""}>${cat}</option>`).join("")}</select><input class="input gold-input" type="number" min="0" value="${Number(t.gold||0)}" placeholder="골드"><button class="remove" onclick="this.closest('.edit-row').remove()">✕</button></div>`;}
function addDaily(){document.getElementById("dailyEditor").insertAdjacentHTML("beforeend",dailyEdit({id:uid("daily"),name:"",target:1,current:0}));}
function addWeekly(cat){document.getElementById("weeklyEditor").insertAdjacentHTML("beforeend",weeklyEdit({id:uid("weekly"),name:"",note:"",category:cat,gold:0,done:false}));}
function saveTasks(){const ck=document.getElementById("taskCharacterKey").value,c=state.activeCharacters.find(x=>x.key===ck);if(!c)return;c.dailyTasks=[...document.querySelectorAll("#dailyEditor .edit-row")].map(r=>({id:r.dataset.id||uid("daily"),name:r.querySelector(".task-name").value.trim(),target:Math.max(1,Number(r.querySelector(".target-input").value||1)),current:Math.max(0,Number(r.dataset.current||0))})).filter(t=>t.name);c.weeklyTasks=[...document.querySelectorAll("#weeklyEditor .edit-row")].map(r=>({id:r.dataset.id||uid("weekly"),name:r.querySelector(".task-name").value.trim(),note:r.querySelector(".task-note").value.trim(),category:r.querySelector(".task-cat").value,gold:Math.max(0,Number(r.querySelector(".gold-input").value||0)),done:r.dataset.done==="1"})).filter(t=>t.name);save();closeModal("taskModal");render();toast("숙제 구성을 저장했습니다.");}
function removeCharacter(){const ck=document.getElementById("taskCharacterKey").value,c=state.activeCharacters.find(x=>x.key===ck);if(!c)return;if(!confirm(`"${c.characterName}"을 숙제판에서 제거할까요?`))return;state.activeCharacters=state.activeCharacters.filter(x=>x.key!==ck);save();closeModal("taskModal");render();}
function resetDaily(){state.activeCharacters.forEach(c=>c.dailyTasks.forEach(t=>t.current=0));state.meta.dailyCycle=dailyCycle();save();render();toast("일일 체크를 초기화했습니다.");}
function resetWeekly(){state.activeCharacters.forEach(c=>c.weeklyTasks.forEach(t=>t.done=false));state.meta.weeklyCycle=weeklyCycle();save();render();toast("주간 체크를 초기화했습니다.");}
function exportData(){const blob=new Blob([JSON.stringify({app:"LOA Homework V9",exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`loa-homework-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}
function resetAll(){if(!confirm("전체 데이터를 초기화할까요?"))return;state=baseState();[STORAGE_KEY,V8_KEY,API_KEY_STORAGE,V8_API_KEY].forEach(k=>localStorage.removeItem(k));closeModal("settingsModal");render();toast("전체 초기화했습니다.");}
function openModal(id){document.getElementById(id).classList.add("open");}function closeModal(id){document.getElementById(id).classList.remove("open");}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),1800);}

document.getElementById("settings").onclick=openSettings;document.getElementById("syncTop").onclick=openSettings;document.getElementById("addCharacter").onclick=openAdd;
document.getElementById("saveSettings").onclick=saveSettings;document.getElementById("syncNow").onclick=syncRoster;
document.getElementById("resetDaily").onclick=resetDaily;document.getElementById("resetWeekly").onclick=resetWeekly;document.getElementById("exportData").onclick=exportData;document.getElementById("resetAll").onclick=resetAll;
document.getElementById("candidateSearch").oninput=renderCandidates;document.getElementById("selectAllCandidates").onclick=selectCandidates;document.getElementById("confirmAdd").onclick=confirmAdd;
document.getElementById("addDailyTask").onclick=addDaily;document.querySelectorAll("[data-weekcat]").forEach(b=>b.onclick=()=>addWeekly(b.dataset.weekcat));document.getElementById("saveTasks").onclick=saveTasks;document.getElementById("removeCharacter").onclick=removeCharacter;
document.querySelectorAll("[data-tasktab]").forEach(b=>b.onclick=()=>{taskTab=b.dataset.tasktab;renderTaskTabs();});
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll(".modal-bg").forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id);});
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filterMode=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderRows();});
document.getElementById("search").oninput=e=>{searchText=e.target.value;renderRows();};
window.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal-bg.open").forEach(m=>closeModal(m.id));});
if(!localStorage.getItem(API_KEY_STORAGE)&&localStorage.getItem(V8_API_KEY))localStorage.setItem(API_KEY_STORAGE,localStorage.getItem(V8_API_KEY));
render();