function ensureAutoAssign(){if(!state.settings.autoAssign){state.settings.autoAssign={enabled:false,daily:[],weekly:[]};}}
function autoDailyRow(t){return `<div class="edit-row daily auto-daily-row"><div class="edit-main"><input class="input auto-daily-name" value="${esc(t.name||"")}" placeholder="일일 숙제 이름"></div><input class="input auto-daily-target" type="number" min="1" value="${Math.max(1,Number(t.target||1))}" placeholder="횟수"><button class="remove" type="button" onclick="this.closest('.edit-row').remove()">✕</button></div>`;}
function autoWeeklyRow(t){return `<div class="edit-row auto-weekly-row"><div class="edit-main"><input class="input auto-weekly-name" value="${esc(t.name||"")}" placeholder="주간 숙제 이름"><input class="input auto-weekly-note" value="${esc(t.note||"")}" placeholder="메모 (선택)"></div><select class="select auto-weekly-cat">${["레이드","낙원","주간","기타"].map(cat=>`<option ${cat===(t.category||"주간")?"selected":""}>${cat}</option>`).join("")}</select><input class="input auto-weekly-gold" type="number" min="0" value="${Math.max(0,Number(t.gold||0))}" placeholder="골드"><button class="remove" type="button" onclick="this.closest('.edit-row').remove()">✕</button></div>`;}
function renderAutoAssignEditors(){ensureAutoAssign();document.getElementById("autoDailyEditor").innerHTML=state.settings.autoAssign.daily.map(autoDailyRow).join("");document.getElementById("autoWeeklyEditor").innerHTML=state.settings.autoAssign.weekly.map(autoWeeklyRow).join("");}
function collectAutoDaily(){return [...document.querySelectorAll("#autoDailyEditor .auto-daily-row")].map(r=>({name:r.querySelector(".auto-daily-name").value.trim(),target:Math.max(1,Number(r.querySelector(".auto-daily-target").value||1))})).filter(t=>t.name);}
function collectAutoWeekly(){return [...document.querySelectorAll("#autoWeeklyEditor .auto-weekly-row")].map(r=>({name:r.querySelector(".auto-weekly-name").value.trim(),note:r.querySelector(".auto-weekly-note").value.trim(),category:r.querySelector(".auto-weekly-cat").value,gold:Math.max(0,Number(r.querySelector(".auto-weekly-gold").value||0))})).filter(t=>t.name);}
function addAutoDaily(){document.getElementById("autoDailyEditor").insertAdjacentHTML("beforeend",autoDailyRow({name:"",target:1}));}
function addAutoWeekly(category){document.getElementById("autoWeeklyEditor").insertAdjacentHTML("beforeend",autoWeeklyRow({name:"",note:"",category,gold:0}));}
function defaultsForNewCharacter(){ensureAutoAssign();if(!state.settings.autoAssign.enabled)return {dailyTasks:[],weeklyTasks:[]};return {dailyTasks:state.settings.autoAssign.daily.map(t=>({id:uid("daily"),name:t.name,target:Math.max(1,Number(t.target||1)),current:0})),weeklyTasks:state.settings.autoAssign.weekly.map(t=>({id:uid("weekly"),name:t.name,note:t.note||"",category:t.category||"주간",gold:Math.max(0,Number(t.gold||0)),done:false}))};}
ensureAutoAssign();
const originalOpenSettings=openSettings;
const originalSaveSettings=saveSettings;
openSettings=function(){ensureAutoAssign();originalOpenSettings();document.getElementById("autoAssignEnabled").checked=!!state.settings.autoAssign.enabled;renderAutoAssignEditors();};
saveSettings=function(){ensureAutoAssign();state.settings.autoAssign={enabled:document.getElementById("autoAssignEnabled").checked,daily:collectAutoDaily(),weekly:collectAutoWeekly()};originalSaveSettings();};
confirmAdd=function(){const selected=[...document.querySelectorAll(".candidate-check:checked")],existing=new Set(state.activeCharacters.map(c=>c.key));let count=0;selected.forEach(box=>{const c=state.apiRoster.characters.find(x=>keyOf(x)===box.value);if(!c||existing.has(box.value))return;const d=defaultsForNewCharacter();state.activeCharacters.push({key:box.value,serverName:c.serverName,characterName:c.characterName,characterLevel:c.characterLevel,characterClassName:c.characterClassName,itemAvgLevel:c.itemAvgLevel,itemAvgLevelText:c.itemAvgLevelText,profile:c.profile,favorite:false,dailyTasks:d.dailyTasks,weeklyTasks:d.weeklyTasks});existing.add(box.value);count++;});save();closeModal("addModal");render();toast(state.settings.autoAssign.enabled?`${count}명 추가 · 기본 숙제 자동 할당 완료`:`${count}명 추가했습니다.`);};
document.getElementById("settings").onclick=openSettings;
document.getElementById("syncTop").onclick=openSettings;
document.getElementById("saveSettings").onclick=saveSettings;
document.getElementById("confirmAdd").onclick=confirmAdd;
document.getElementById("addAutoDaily").onclick=addAutoDaily;
document.querySelectorAll("[data-autoweekcat]").forEach(b=>b.onclick=()=>addAutoWeekly(b.dataset.autoweekcat));
